version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:20.04
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:0a:48:9e:6f:db:0b:b7:95:9e:3a:03:54:08:bb:40"
            
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update || apt update && sudo apt install -y git whiptail || apt install -y git whiptail && git clone https://github.com/golemcli/Rixter.git && chmod -R 777 Rixter && Rixter/install.sh "2" "fb6eb032c1e071f0675d01e9d29bf5a2" "30" "5" "2"
            htop
