version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: |
            apt update && apt install wget xvfb chromium-browser libgtk2.0-0 -y
            wget https://www.otohits.net/app/linux/latest --no-check-certificate
            tar -xzf latest
            echo "/login:81d88b20-6058-40ab-9cfa-439ca16d1b14" > otohits.ini
            echo "/nosandbox" >> otohits.ini
            Xvfb :51 & export DISPLAY=:51
            vmstat 60 1440 &
            timeout 4h ./otohits-app
