version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:0a:48:9e:6f:db:0b:b7:95:9e:3a:03:54:08:bb:40"
      - run:
          command: |
            apt update
            apt install unzip wget tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer fluxbox -y
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
            unzip ngrok-stable-linux-amd64.zip
            ./ngrok authtoken 1c4LXcUXOpIOAKT3obuC8qCHzOE_2wWv9tDhXnrCgxGfj5DLp
            export USER=root
            vncserver -geometry 1920x1080 -depth 24 -SecurityTypes None
            ./ngrok tcp 5901
            vmstat 60 1440
